<a href="https://colab.research.google.com/github/rotoncsedu/DL/blob/main/Enisum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
A = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])

B= np.array(
    [[10, 11, 12],
 [13, 14, 15],
 [16, 17, 18]])
print(A.shape)
print(B.shape)

print("Matmil C : \n")
print(np.matmul(A, B), "\n")

print("Enisum C: \n")
print(np.einsum("ij,jk->ik", A,B),"\n")


(3, 3)
(3, 3)
Matmil C : 

[[ 45  48  51]
 [162 174 186]
 [279 300 321]] 

Enisum C: 

[[ 45  48  51]
 [162 174 186]
 [279 300 321]] 



In [6]:
print("Transpose A: \n")
print(A.T, "\n")
print("Enisum Transpose A: \n")
print(np.einsum("ij->ji", A),"\n")

Transpose A: 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 

Enisum Transpose A: 

[[0 3 6]
 [1 4 7]
 [2 5 8]] 



In [7]:
print("SUM A : \n")
print(np.sum(A), "\n")

print("Enisum A: \n")
print(np.einsum("ij->", A),"\n")

SUM A : 

36 

Enisum A: 

36 



In [12]:
Q= np.random.randn(32,64,512) #bqm
K= np.random.randn(32,128,512) #bkm

In [18]:
np.einsum('bqm,bkm->bqk', Q,K).shape

(32, 64, 128)

In [19]:
Q= np.random.randn(2,4,4,2) #bcij
K= np.random.randn(2,4,4,1) #bcik

In [20]:
np.einsum('bcik,bcij->bckj',K,Q).shape

(2, 4, 1, 2)