<a href="https://colab.research.google.com/github/rotoncsedu/DL/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [6]:
x1 = tf.constant(
    [[1, 2, 0],
     [3, 5, -1]]
)

x2 = tf.constant(
    [[37, -3, 0],
     [3, 5, 7],
     [4,5,6]]
)

In [7]:
tf.linalg.matmul(x1, x2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 43,   7,  14],
       [122,  11,  29]], dtype=int32)>

In [8]:
print(x1.shape, x2.shape)

(2, 3) (3, 3)


x1@x2   // Matrix multiplication

In [10]:
x1 @ x2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 43,   7,  14],
       [122,  11,  29]], dtype=int32)>

In [13]:
tf.linalg.matmul(
    x1,
    x2,
    transpose_a=False,
    transpose_b=True,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    grad_a=False,
    grad_b=False,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[31, 13, 14],
       [96, 27, 31]], dtype=int32)>

In [19]:
## Lower Band
x1_lower_band = tf.linalg.band_part(x1, 0, 1)
print(x1_lower_band)


tf.Tensor(
[[ 1  2  0]
 [ 0  5 -1]], shape=(2, 3), dtype=int32)


In [20]:
## Upper band
x1_upper_band = tf.linalg.band_part(x1, -1, 0)
print(x1_upper_band)

tf.Tensor(
[[1 0 0]
 [3 5 0]], shape=(2, 3), dtype=int32)


In [24]:
x2 = tf.constant(
    [[37, -3, 0],
     [3, 5, 7],
     [4,5,6]], dtype = float
)
print(x2)
x2_inv = tf.linalg.inv(x2)
print(x2_inv)

tf.Tensor(
[[37. -3.  0.]
 [ 3.  5.  7.]
 [ 4.  5.  6.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.02325581 -0.08372094  0.09767442]
 [-0.04651164 -1.0325582   1.2046512 ]
 [ 0.02325583  0.9162791  -0.90232563]], shape=(3, 3), dtype=float32)


In [26]:
x2_identity = x2 @ x2_inv
print(x2_identity)

tf.Tensor(
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 2.9802322e-08  9.9999928e-01  0.0000000e+00]
 [ 0.0000000e+00 -4.7683716e-07  1.0000000e+00]], shape=(3, 3), dtype=float32)


SVD


In [27]:
s,v,d = tf.linalg.svd(x2)
print(s)
print(v)
print(d)

tf.Tensor([37.41136    11.753759    0.48894364], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.9914295  -0.12840682 -0.02406948]
 [ 0.07855321  0.73313564 -0.67553025]
 [ 0.10438894  0.66784996  0.73693913]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.9979883   0.01018863  0.06257313]
 [-0.05505219  0.62874764  0.7756583 ]
 [ 0.03143981  0.7775427  -0.6280437 ]], shape=(3, 3), dtype=float32)
